### ISSUE TITLE
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by agrron** [dusty-nv/jetson-containers#362]
Error encountered while building onnx.
Operating System: Windows 11
Version Manager:conda  23.7.4
Python: 3.11.7
Other versions: 
Package           Version
---------------- -----------
anyio             4.2.0
argcomplete       3.2.1
astor             0.8.1
certifi           2023.11.17
cmake             3.28.1
decorator         5.1.1
h11               0.14.0
httpcore          1.0.2
httpx             0.26.0
idna              3.6
mkl-fft           1.3.8
mkl-random        1.2.4
mkl-service       2.4.0
numpy             1.26.3
onnx              1.13.1
opt-einsum        3.3.0
paddlepaddle      2.6.0
pillow            10.2.0
pip               23.3.1
pipx              1.3.3
platformdirs      4.1.0
protobuf          3.20.2
setuptools        68.2.2
six               1.16.0
sniffio           1.3.0
typing_extensions 4.9.0
userpath          1.9.1
wheel             0.41.2
---------------- -----------
Error Message:

`Building wheels for collected packages: onnx
  Building wheel for onnx (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for onnx (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [87 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\dist.py:472: SetuptoolsDeprecationWarning: Invalid dash-separated options
            ********************************************************************************
            Usage of dash-separated 'license-file' will not be supported in future
            versions. Please use the underscore name 'license_file' instead.

            By 2024-Sep-26, you need to update your project and remove deprecated calls
            or your builds will no longer be supported.

            See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
            ********************************************************************************
        opt = self.warn_dash_deprecation(opt, section)
      running bdist_wheel
      running build
      running build_py
      running create_version
      running cmake_build
      Using cmake args: ['C:\\Users\\admin\\anaconda3\\envs\\paddleOcr\\Scripts\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\admin\\anaconda3\\envs\\paddleOcr\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\admin\\anaconda3\\envs\\paddleOcr\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp311-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.11', '-DONNX_USE_MSVC_STATIC_RUNTIME=ON', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-e13bq768\\onnx_c112a577e4db404ba8cdefe533083a9b']
      Traceback (most recent call last):
        File "<frozen runpy>", line 198, in _run_module_as_main
        File "<frozen runpy>", line 88, in _run_code
        File "C:\Users\admin\anaconda3\envs\paddleOcr\Scripts\cmake.exe\__main__.py", line 4, in <module>
      ModuleNotFoundError: No module named 'cmake'
      Traceback (most recent call last):
        File "C:\Users\admin\anaconda3\envs\paddleOcr\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\admin\anaconda3\envs\paddleOcr\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\admin\anaconda3\envs\paddleOcr\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\build_meta.py", line 404, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 337, in <module>
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 233, in run
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\admin\AppData\Local\Temp\pip-build-env-si86u3u4\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 219, in run
        File "C:\Users\admin\anaconda3\envs\paddleOcr\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Users\\admin\\anaconda3\\envs\\paddleOcr\\Scripts\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Users\\admin\\anaconda3\\envs\\paddleOcr\\include', '-DPYTHON_EXECUTABLE=C:\\Users\\admin\\anaconda3\\envs\\paddleOcr\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp311-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.11', '-DONNX_USE_MSVC_STATIC_RUNTIME=ON', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\admin\\AppData\\Local\\Temp\\pip-install-e13bq768\\onnx_c112a577e4db404ba8cdefe533083a9b']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnx
Failed to build onnx
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects`

**Comment by dusty-nv** [comment]
> Operating System: Windows 11
> Version Manager:conda 23.7.4

Hi @agrron, I'm sorry, this repo is for supporting ARM64+CUDA on Linux for Jetson devices.  It appears you are using Windows and I would recommending filing your issue against the upstream onnx github.
