### ISSUE TITLE
Options for building on host PC (Cross compilation)

### ISSUE THREAD

**Issue by BBO-TheyeQ** [dusty-nv/jetson-containers#377]
I'm new in this area and I'm wondering if there are some specific options to pass through the building script to use it on a host PC instead of directly building on Jetson Orin ?
When I do a simple test on my host PC (x86/Ubuntu) with : 
./build.sh --name=my_container pytorch transformers ros:humble-desktop

I'm getting error with ARCH and L4T_VERSION (and likely more) as these parameters are not reporting values corresponding to my Jetson Orin.

./build.sh --name=my_container pytorch transformers ros:humble-desktop
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/benoitb/nvidia/jetson-containers/jetson_containers/__init__.py", line 7, in <module>
    from .logging import *
  File "/home/benoitb/nvidia/jetson-containers/jetson_containers/logging.py", line 5, in <module>
    from .packages import _PACKAGE_ROOT
  File "/home/benoitb/nvidia/jetson-containers/jetson_containers/packages.py", line 12, in <module>
    from .l4t_version import L4T_VERSION
  File "/home/benoitb/nvidia/jetson-containers/jetson_containers/l4t_version.py", line 77, in <module>
    def get_jetpack_version(l4t_version=get_l4t_version(), default='5.1'):
  File "/home/benoitb/nvidia/jetson-containers/jetson_containers/l4t_version.py", line 37, in get_l4t_version
    raise ValueError(f"L4T_VERSION isn't supported on {ARCH} architecture (aarch64 only)")
NameError: name 'ARCH' is not defined

**Comment by dusty-nv** [comment]
Hi @BBO-TheyeQ, although there is a [cross-compilation container](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/jetpack-linux-aarch64-crosscompile-x86) for JetPack (which includes cross-compilation support for applications using the libraries in JetPack like CUDA, cuDNN, TensorRT, ect), there are so many 3rd-parties used in the various jetson-containers (each of which would typically require some kind of cross-compilation support) that it's impractical.  Also jetson-containers performs tests throughout the build process that use the GPU to verify the packages were built correctly, which necessitates running onboard actual Jetson hardware.   I build the containers on Jetson AGX Orin or Xavier which is pretty fast enough.
