### ISSUE TITLE
building an image of ros-foxy-desktop

### ISSUE THREAD

**Issue by bigrobinson** [dusty-nv/jetson-containers#38]
I replace change the value of the argument ROS_PKG from "ros_base" to "desktop" (and change the tag in the build script correspondingly) and get the following error after cloning into demos:

ERROR: Rosdep experienced an error: Multiple packages found with the same name "demo_nodes_cpp":

demo_nodes_cpp
demos/demo_nodes_cpp
Multiple packages found with the same name "demo_nodes_py":
demo_nodes_py
demos/demo_nodes_py
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep
rosdep version: 0.20.0

Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 144, in rosdep_main
exit_code = _rosdep_main(args)
File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 430, in _rosdep_main
return _package_args_handler(command, parser, options, args)
File "/usr/lib/python3/dist-packages/rosdep2/main.py", line 485, in _package_args_handler
pkgs = find_catkin_packages_in(path, options.verbose)
File "/usr/lib/python3/dist-packages/rosdep2/catkin_packages.py", line 33, in find_catkin_packages_in
packages = find_packages(path)
File "/usr/lib/python3/dist-packages/catkin_pkg/packages.py", line 96, in find_packages
raise RuntimeError('\n'.join(duplicates))
RuntimeError: Multiple packages found with the same name "demo_nodes_cpp":

demo_nodes_cpp
demos/demo_nodes_cpp
Multiple packages found with the same name "demo_nodes_py":
demo_nodes_py
demos/demo_nodes_py

**Comment by bigrobinson** [comment]
Sorry, I think I found the issue. In your Dockerfile, you are cloning the demos directory to include in the build. When you build the full desktop version it apparently pulls demos anyway, so it seems I ended up with two copies. Changing ROS_PKG from "ros_base" to "desktop" and commenting out the following lines. It seems to be working so far.

    git clone --branch ${ROS_DISTRO} https://github.com/ros2/demos demos && \
    cp -r demos/demo_nodes_cpp ${ROS_ROOT}/src && \
    cp -r demos/demo_nodes_py ${ROS_ROOT}/src && \
    rm -r -f demos

In addition you can add rti-connext-dds-* to the the apt-get install block to get that support if desired and avoid some red stderr outputs.
