### ISSUE TITLE
Failure trying to build container

### ISSUE THREAD

**Issue by bryanhughes** [dusty-nv/jetson-containers#415]
Using
```
$ ./build.sh --name=my_container local_llm
```
It fails to build
```
<clipped output>

-- Building container my_container:r36.2.0-faiss

DOCKER_BUILDKIT=0 docker build --network=host --tag my_container:r36.2.0-faiss \
--file /mnt/git/jetson-containers/packages/vectordb/faiss/Dockerfile \
--build-arg BASE_IMAGE=my_container:r36.2.0-cuda-python \
--build-arg BUILD_IMAGE="None" \
/mnt/git/jetson-containers/packages/vectordb/faiss \
2>&1 | tee /mnt/git/jetson-containers/logs/20240308_175241/build/my_container_r36.2.0-faiss.txt; exit ${PIPESTATUS[0]}

DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
            BuildKit is currently disabled; enable it by removing the DOCKER_BUILDKIT=0
            environment-variable.

Sending build context to Docker daemon  24.58kB
Step 1/11 : ARG BASE_IMAGE
Step 2/11 : ARG BUILD_IMAGE
Step 3/11 : FROM ${BUILD_IMAGE} as builder
invalid reference format: repository name (library/None) must be lowercase
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/git/jetson-containers/jetson_containers/build.py", line 102, in <module>
    build_container(args.name, args.packages, args.base, args.build_flags, args.simulate, args.skip_tests, args.test_only, args.push, args.no_github_api)
  File "/mnt/git/jetson-containers/jetson_containers/container.py", line 143, in build_container
    status = subprocess.run(cmd.replace(_NEWLINE_, ' '), executable='/bin/bash', shell=True, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'DOCKER_BUILDKIT=0 docker build --network=host --tag my_container:r36.2.0-faiss --file /mnt/git/jetson-containers/packages/vectordb/faiss/Dockerfile --build-arg BASE_IMAGE=my_container:r36.2.0-cuda-python --build-arg BUILD_IMAGE="None" /mnt/git/jetson-containers/packages/vectordb/faiss 2>&1 | tee /mnt/git/jetson-containers/logs/20240308_175241/build/my_container_r36.2.0-faiss.txt; exit ${PIPESTATUS[0]}' returned non-zero exit status 1.
```

**Comment by dusty-nv** [comment]
sorry @bryanhughes, I just pushed `dustynv/faiss:be12427-builder-r36.2.0` image and updated the container index - can you do a `git pull` and try again?
