### ISSUE TITLE
jetson-containers build [package] results in error

### ISSUE THREAD

**Issue by Stuveman** [dusty-nv/jetson-containers#551]
Hello, I did the whole setup guide with setting up docker, cloning the repo and executing the install script.
(I'm using the Nvidia Jetson AGX Orin)
I want to adjust the dockerfile in jetson-containers/packages/audio/whisper/Dockerfile for installing additional Ubnutu packages. So I wanted to create a new docker image with **jetson-containers build whisper** but I ran into following errors:
```
$ jetson-containers build whisper
Namespace(packages=['whisper'], name='', base='', multiple=False, build_flags='', package_dirs=[''], list_packages=False, show_packages=False, skip_packages=[''], skip_errors=False, skip_tests=[''], test_only=[''], simulate=False, push='', logs='', verbose=False, no_github_api=False)
-- L4T_VERSION=36.3.0
-- JETPACK_VERSION=6.0
-- CUDA_VERSION=12.5
-- PYTHON_VERSION=3.10
-- LSB_RELEASE=22.04 (jammy)
-- Package ros:noetic-ros-base has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ros:noetic-ros-core has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ros:noetic-desktop has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ros:foxy-ros-base has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ros:foxy-ros-core has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ros:foxy-desktop has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ros:galactic-ros-base has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ros:galactic-ros-core has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ros:galactic-desktop has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ros:humble-ros-base has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ros:humble-ros-core has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ros:humble-desktop has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ros:iron-ros-base has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ros:iron-ros-core has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ros:iron-desktop has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package tritonserver has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ctranslate2:master has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ctranslate2:master-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ctranslate2:4.2.0 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package ctranslate2:4.2.0-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package cupy has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package pycuda has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package nemo has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package nanosam has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package nanoowl has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package sam has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package efficientvit has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package tam has missing dependencies, disabling...  ("couldn't find package:  sam")
-- Package onnxruntime:1.19 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package onnxruntime:1.19-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package l4t-diffusion has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package l4t-text-generation has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package l4t-tensorflow:tf1 has missing dependencies, disabling...  ("couldn't find package:  tensorflow")
-- Package l4t-tensorflow:tf2 has missing dependencies, disabling...  ("couldn't find package:  pycuda")
-- Package l4t-ml has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package l4t-pytorch has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package openai-triton:2.1.0 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package openai-triton:2.1.0-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package deepstream has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package arrow:14.0.1 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package arrow:12.0.1 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package arrow:5.0.0 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package numba has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package xtts has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package audiocraft has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package voicecraft has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package whisper_trt has missing dependencies, disabling...  ("couldn't find package:  onnxruntime")
-- Package faster-whisper has missing dependencies, disabling...  ("couldn't find package:  ctranslate2")
-- Package whisperx has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package piper-tts has missing dependencies, disabling...  ("couldn't find package:  onnxruntime")
-- Package whisper has missing dependencies, disabling...  ("couldn't find package:  numba")
-- Package jetson-inference has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package torch2trt has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package torch_tensorrt has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package torchvision:0.16.2 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package torchvision:0.16.2-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package torchvision:0.17.2 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package torchvision:0.17.2-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package torchvision:0.18.0 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package torchvision:0.18.0-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package torchaudio:2.1.0 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package torchaudio:2.1.0-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package torchaudio:2.2.2 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package torchaudio:2.2.2-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package torchaudio:2.3.0 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package torchaudio:2.3.0-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package pytorch:2.1 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package pytorch:2.1-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package pytorch:2.2 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package pytorch:2.2-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package pytorch:2.3 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package pytorch:2.3-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package opencv:4.8.1 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package opencv:4.8.1-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package opencv:4.9.0 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package opencv:4.9.0-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package opencv:4.8.1-deb has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package wyoming-piper:master has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package wyoming-whisper:latest has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package stable-diffusion has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package stable-diffusion-webui has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package jetcam has missing dependencies, disabling...  ("couldn't find package:  opencv")
-- Package zed has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package realsense has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package jetson-utils has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package faiss:1.7.3 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package faiss:1.7.3-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package faiss:1.7.4 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package faiss:1.7.4-builder has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package faiss_lite has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package nanodb has missing dependencies, disabling...  ("couldn't find package:  faiss_lite")
-- Package cudf:23.10.03 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package cuml has missing dependencies, disabling...  ("couldn't find package:  cudf")
-- Package raft has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package langchain has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package langchain:samples has missing dependencies, disabling...  ("couldn't find package:  langchain:main")
-- Package jetrag has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package llama-index has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package llama-index:samples has missing dependencies, disabling...  ("couldn't find package:  llama-index:main")
-- Package transformers has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package transformers:git has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package transformers:nvgpt has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package llama_cpp:0.2.57 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package llama_cpp:0.2.70 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package gptq-for-llama has missing dependencies, disabling...  ("couldn't find package:  transformers")
-- Package nano_llm:main has missing dependencies, disabling...  ("couldn't find package:  nanodb")
-- Package nano_llm:24.4 has missing dependencies, disabling...  ("couldn't find package:  nanodb")
-- Package nano_llm:24.4.1 has missing dependencies, disabling...  ("couldn't find package:  nanodb")
-- Package nano_llm:24.5 has missing dependencies, disabling...  ("couldn't find package:  nanodb")
-- Package nano_llm:24.5.1 has missing dependencies, disabling...  ("couldn't find package:  nanodb")
-- Package bitsandbytes:0.39.1 has missing dependencies, disabling...  ("couldn't find package:  transformers")
-- Package bitsandbytes:0.39.1-builder has missing dependencies, disabling...  ("couldn't find package:  transformers")
-- Package local_llm has missing dependencies, disabling...  ("couldn't find package:  nanodb")
-- Package xformers:0.0.26 has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package xformers:0.0.26-builder has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package text-generation-webui:main has missing dependencies, disabling...  ("couldn't find package:  transformers")
-- Package text-generation-webui:1.7 has missing dependencies, disabling...  ("couldn't find package:  transformers")
-- Package text-generation-webui:6a7cd01 has missing dependencies, disabling...  ("couldn't find package:  transformers")
-- Package mlc:0.1.0 has missing dependencies, disabling...  ("couldn't find package:  transformers")
-- Package mlc:0.1.0-builder has missing dependencies, disabling...  ("couldn't find package:  transformers")
-- Package mlc:0.1.1 has missing dependencies, disabling...  ("couldn't find package:  transformers")
-- Package mlc:0.1.1-builder has missing dependencies, disabling...  ("couldn't find package:  transformers")
-- Package minigpt4 has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package exllama:0.0.15 has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package text-generation-inference has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package ollama has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package tensorrt_llm:0.11.dev0 has missing dependencies, disabling...  ("couldn't find package:  tensorrt")
-- Package tensorrt_llm:0.11.dev0-builder has missing dependencies, disabling...  ("couldn't find package:  tensorrt")
-- Package tensorrt_llm:0.10.dev0 has missing dependencies, disabling...  ("couldn't find package:  tensorrt")
-- Package tensorrt_llm:0.10.dev0-builder has missing dependencies, disabling...  ("couldn't find package:  tensorrt")
-- Package auto_gptq:0.7.1 has missing dependencies, disabling...  ("couldn't find package:  transformers")
-- Package optimum has missing dependencies, disabling...  ("couldn't find package:  onnxruntime")
-- Package llava has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package awq:0.1.0 has missing dependencies, disabling...  ("couldn't find package:  transformers")
-- Package awq:0.1.0-builder has missing dependencies, disabling...  ("couldn't find package:  transformers")
-- Package flash-attention:2.5.6 has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package flash-attention:2.5.6-builder has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package flash-attention:2.5.7 has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package flash-attention:2.5.7-builder has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package auto_awq:0.2.4 has missing dependencies, disabling...  ("couldn't find package:  transformers")
-- Package tvm has missing dependencies, disabling...  ("couldn't find package:  pytorch")
-- Package tensorflow2 has missing dependencies, disabling...  ("couldn't find package:  cuda")
-- Package gstreamer has missing dependencies, disabling...  ("couldn't find package:  opencv")
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/media/jetson/ExtraStorage/jetson-containers/jetson_containers/build.py", line 103, in <module>
    build_container(args.name, args.packages, args.base, args.build_flags, args.simulate, args.skip_tests, args.test_only, args.push, args.no_github_api)
  File "/media/jetson/ExtraStorage/jetson-containers/jetson_containers/container.py", line 66, in build_container
    packages = resolve_dependencies(packages)
  File "/media/jetson/ExtraStorage/jetson-containers/jetson_containers/packages.py", line 316, in resolve_dependencies
    packages, changed = add_depends(packages)
  File "/media/jetson/ExtraStorage/jetson-containers/jetson_containers/packages.py", line 288, in add_depends
    for dependency in find_package(package).get('depends', []):
  File "/media/jetson/ExtraStorage/jetson-containers/jetson_containers/packages.py", line 174, in find_package
    raise KeyError(f"couldn't find package:  {package}")
KeyError: "couldn't find package:  whisper"
```
Also tried other packages like pytorch but the result was always the same, that the package couldn't be found.
But running **jetson-containers run $(autotag whisper)** works without any issues:
```
jetson-containers run $(autotag whisper)
Namespace(packages=['whisper'], prefer=['local', 'registry', 'build'], disable=[''], user='dustynv', output='/tmp/autotag', quiet=False, verbose=False)
-- L4T_VERSION=36.3.0  JETPACK_VERSION=6.0  CUDA_VERSION=12.5
-- Finding compatible container image for ['whisper']
...
```
Would appreciate any help.

**Comment by dusty-nv** [comment]
Hi @Stuveman , can you try running this like `CUDA_VERSION=12.2 jetson-containers build whisper` ?

**Comment by Stuveman** [comment]
Hey @dusty-nv , worked like a charm, thank you so much. Kinda mad at myself at how easy it was to solve.

**Comment by dusty-nv** [comment]
Oh don't be, sorry i think that is a bug on my end, because I detect what version of CUDA is installed on the host, when really that should not matter at all.  I have a TODO to remove that and just use a lookup table for what the default version of CUDA should be for each jetpack...
