### ISSUE TITLE
Compatibility problems when trying to run ROS2 packages

### ISSUE THREAD

**Issue by pizgloria** [dusty-nv/jetson-containers#56]
Hello,

I am a beginner in ROS2. I installed the container for ROS2 Eloquent and tested the image with the scripts. Everything seems to be fine.

In my container I installed a lot of tools (python, pip, torch) etc, and then proceeded to install some of the packages mentioned [here](https://developer.nvidia.com/blog/implementing-robotics-applications-with-ros-2-and-ai-on-jetson-platform-2/). I am using a JetBot.

However, I cannot run any of the packages, and I get the same error message for every one of them. It says:

`Failed to load entry point 'launch': cannot import name 'InvalidLaunchFileError'
Traceback (most recent call last):
  File "/opt/ros/eloquent/bin/ros2", line 11, in <module>
    load_entry_point('ros2cli==0.8.8', 'console_scripts', 'ros2')()
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ros2cli/cli.py", line 45, in main
    required=False)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ros2cli/command/__init__.py", line 112, in add_subparsers
    command_parser, '{cli_name} {name}'.format_map(locals()))
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ros2topic/command/topic.py", line 32, in add_arguments
    parser, cli_name, '_verb', verb_extensions, required=False)
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ros2cli/command/__init__.py", line 112, in add_subparsers
    command_parser, '{cli_name} {name}'.format_map(locals()))
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ros2topic/verb/echo.py", line 63, in add_arguments
    parser, is_publisher=False, default_preset='sensor_data')
  File "/opt/ros/eloquent/lib/python3.6/site-packages/ros2topic/api/__init__.py", line 198, in add_qos_arguments_to_argument_parser
    .format(verb, default_profile.reliability.short_key))
AttributeError: 'QoSReliabilityPolicy' object has no attribute 'short_key'`

Any ideas on what this could mean?

Thank you.

**Comment by eddiem3** [comment]
That looks more like an error w/ a specific ROS2 package than an issue w/ the container.
