### ISSUE TITLE
Building a piper container on Jetpack 6.1 produces an error

### ISSUE THREAD

**Issue by bogdanr** [dusty-nv/jetson-containers#667]
Full log below:
```
bogdan@jetson:~/jetson-containers$ jetson-containers run $(autotag piper)
Namespace(packages=['piper'], prefer=['local', 'registry', 'build'], disable=[''], user='dustynv', output='/tmp/autotag', quiet=False, verbose=False)
-- L4T_VERSION=36.4.0  JETPACK_VERSION=6.1  CUDA_VERSION=12.6
-- Finding compatible container image for ['piper']

Couldn't find a compatible container for piper, would you like to build it? [y/N] y
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/bogdan/jetson-containers/jetson_containers/tag.py", line 58, in <module>
    image = find_container(args.packages[0], prefer_sources=args.prefer, disable_sources=args.disable, user=args.user, quiet=args.quiet)
  File "/home/bogdan/jetson-containers/jetson_containers/container.py", line 537, in find_container
    return build_container('', package) #, simulate=True)
  File "/home/bogdan/jetson-containers/jetson_containers/container.py", line 66, in build_container
    packages = resolve_dependencies(packages)
  File "/home/bogdan/jetson-containers/jetson_containers/packages.py", line 316, in resolve_dependencies
    packages, changed = add_depends(packages)
  File "/home/bogdan/jetson-containers/jetson_containers/packages.py", line 288, in add_depends
    for dependency in find_package(package).get('depends', []):
  File "/home/bogdan/jetson-containers/jetson_containers/packages.py", line 174, in find_package
    raise KeyError(f"couldn't find package:  {package}")
KeyError: "couldn't find package:  piper"
-- Error:  return code 1
V4L2_DEVICES: 
csi_indexes: 
/home/bogdan/jetson-containers/run.sh: line 194: /tmp/nv_jetson_model: Permission denied
+ sudo docker run --runtime nvidia -it --rm --network host --shm-size=8g --volume /tmp/argus_socket:/tmp/argus_socket --volume /etc/enctune.conf:/etc/enctune.conf --volume /etc/nv_tegra_release:/etc/nv_tegra_release --volume /tmp/nv_jetson_model:/tmp/nv_jetson_model --volume /var/run/dbus:/var/run/dbus --volume /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket --volume /var/run/docker.sock:/var/run/docker.sock --volume /home/bogdan/jetson-containers/data:/data --device /dev/snd --device /dev/bus/usb --device /dev/i2c-0 --device /dev/i2c-1 --device /dev/i2c-2 --device /dev/i2c-4 --device /dev/i2c-5 --device /dev/i2c-7 --device /dev/i2c-9 --name my_jetson_container
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Create and run a new container from an image
+ set +x
```

**Comment by bogdanr** [comment]
The issue was that I needed to specify wyoming-piper instead of just piper.
