### ISSUE TITLE
Could not load dynamic library 'libcudart.so.10.2'

### ISSUE THREAD

**Issue by sawk1** [dusty-nv/jetson-containers#72]
Hi, im trying to up this docker on my jetson nano, but its show me this error

```
detector_1  | INFO:flocal.cli:Warming up 1 processes
detector_1  | INFO:flocal.cli:Waiting for warmup to complete
detector_1  | 2021-07-01 19:37:26.444182: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.10.2'; dlerror: libcudart.so.10.2: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda-10.2/targets/aarch64-linux/lib:
detector_1  | 2021-07-01 19:37:26.444238: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
detector_1  | 2021-07-01 19:37:26.444637: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.10.2'; dlerror: libcudart.so.10.2: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda-10.2/targets/aarch64-linux/lib:
detector_1  | 2021-07-01 19:37:26.444706: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
detector_1  | Traceback (most recent call last):
detector_1  |   File "/usr/local/bin/detector-cli", line 33, in <module>
detector_1  |     sys.exit(load_entry_point('flocal-detector==0.0.0', 'console_scripts', 'detector-cli')())
detector_1  |   File "/usr/local/lib/python3.6/dist-packages/click-8.0.1-py3.6.egg/click/core.py", line 1137, in __call__
detector_1  |     return self.main(*args, **kwargs)
detector_1  |   File "/usr/local/lib/python3.6/dist-packages/click-8.0.1-py3.6.egg/click/core.py", line 1062, in main
detector_1  |     rv = self.invoke(ctx)
detector_1  |   File "/usr/local/lib/python3.6/dist-packages/click-8.0.1-py3.6.egg/click/core.py", line 1668, in invoke
detector_1  |     return _process_result(sub_ctx.command.invoke(sub_ctx))
detector_1  |   File "/usr/local/lib/python3.6/dist-packages/click-8.0.1-py3.6.egg/click/core.py", line 1404, in invoke
detector_1  |     return ctx.invoke(self.callback, **ctx.params)
detector_1  |   File "/usr/local/lib/python3.6/dist-packages/click-8.0.1-py3.6.egg/click/core.py", line 763, in invoke
detector_1  |     return __callback(*args, **kwargs)
detector_1  |   File "/usr/local/lib/python3.6/dist-packages/flocal_detector-0.0.0-py3.6.egg/detector/cli.py", line 101, in server
detector_1  |   File "/usr/local/lib/python3.6/dist-packages/flocal_detector-0.0.0-py3.6.egg/detector/cli.py", line 101, in <listcomp>
detector_1  |   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
detector_1  |     return self.__get_result()
detector_1  |   File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
detector_1  |     raise self._exception
detector_1  | concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

```

**Comment by dusty-nv** [comment]
Are you trying to build one of the containers from this repo, or run one of them?   If you are running them manually, did you start it with `--runtime nvidia`?

**Comment by sawk1** [comment]
Thank you very much!
i add  `runtime : nvidia ` in my docker-compose.yaml
and now it works thank you so much
