### ISSUE TITLE
[Help wanted] could not download the Stack_D4 data from google drive in openvla project 

### ISSUE THREAD

**Issue by HRXWEB** [dusty-nv/jetson-containers#741]
**Hardware**
- AGX orin 32 GB dev kit

**Software**
- Jetpack 6.1
- L4T 36.4.0

When I run the 

**Command**

```bash
jetson-containers run $(autotag nano_llm)   python3 -m mimicgen.generate       --tasks Stack_D4       --episodes 100       --output /data/datasets/mimicgen       --cameras agentview       --camera-width 224       --camera-height 224
```

The console will print

**Error**

```plain text 
Namespace(packages=['nano_llm'], prefer=['local', 'registry', 'build'], disable=[''], user='dustynv', output='/tmp/autotag', quiet=False, verbose=False)
-- L4T_VERSION=36.4.0  JETPACK_VERSION=6.1  CUDA_VERSION=12.6
-- Finding compatible container image for ['nano_llm']
dustynv/nano_llm:r36.4.0
V4L2_DEVICES: 
+ docker run --runtime nvidia -it --rm --network host --shm-size=8g --volume /tmp/argus_socket:/tmp/argus_socket --volume /etc/enctune.conf:/etc/enctune.conf --volume /etc/nv_tegra_release:/etc/nv_tegra_release --volume /tmp/nv_jetson_model:/tmp/nv_jetson_model --volume /var/run/dbus:/var/run/dbus --volume /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket --volume /var/run/docker.sock:/var/run/docker.sock --volume /workspace/openvla/jetson-containers/data:/data -v /etc/localtime:/etc/localtime:ro -v /etc/timezone:/etc/timezone:ro --device /dev/snd -e PULSE_SERVER=unix:/run/user/1000/pulse/native -v /run/user/1000/pulse:/run/user/1000/pulse --device /dev/bus/usb --device /dev/i2c-0 --device /dev/i2c-1 --device /dev/i2c-2 --device /dev/i2c-3 --device /dev/i2c-4 --device /dev/i2c-5 --device /dev/i2c-6 --device /dev/i2c-7 --device /dev/i2c-8 --device /dev/i2c-9 -v /run/jtop.sock:/run/jtop.sock --name jetson_container_20241206_101947 -e http_proxy=http://192.168.3.242:2888 -e https_proxy=http://192.168.3.242:2888 dustynv/nano_llm:r36.4.0 python3 -m mimicgen.generate --tasks Stack_D4 --episodes 100 --output /data/datasets/mimicgen --cameras agentview --camera-width 224 --camera-height 224
[robosuite WARNING] No private macro file found! (macros.py:53)
[robosuite WARNING] It is recommended to use a private macro file (macros.py:54)
[robosuite WARNING] To setup, run: python /opt/robosuite/robosuite/scripts/setup_macros.py (macros.py:55)
WARNING: robosuite task zoo environments not imported, possibly because robosuite_task_zoo is not installed...
Got error: No module named 'robosuite_task_zoo'
ROBOMIMIC WARNING(
    No private macro file found!
    It is recommended to use a private macro file
    To setup, run: python /opt/robomimic/robomimic/scripts/setup_macros.py
)
Namespace(tasks=['Stack_D4'], episodes=100, cameras=['agentview'], camera_width=224, camera_height=224, cache='/data/datasets/mimicgen', output='/data/datasets/mimicgen', parallel=None, simulate=False, seed=None)

Downloading dataset stack for tasks ['Stack_D4']

RUN python3 -m mimicgen.scripts.download_datasets --download_dir /data/datasets/mimicgen --dataset_type source --tasks stack 

[robosuite WARNING] No private macro file found! (macros.py:53)
[robosuite WARNING] It is recommended to use a private macro file (macros.py:54)
[robosuite WARNING] To setup, run: python /opt/robosuite/robosuite/scripts/setup_macros.py (macros.py:55)
WARNING: robosuite task zoo environments not imported, possibly because robosuite_task_zoo is not installed...
Got error: No module named 'robosuite_task_zoo'
ROBOMIMIC WARNING(
    No private macro file found!
    It is recommended to use a private macro file
    To setup, run: python /opt/robomimic/robomimic/scripts/setup_macros.py
)

Downloading dataset:
    dataset type: source
    task: stack
    download path: /data/datasets/mimicgen/source/stack.hdf5

/usr/local/lib/python3.10/dist-packages/gdown/download.py:33: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = bs4.BeautifulSoup(line, features="html.parser")
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gdown/download.py", line 267, in download
    url = get_url_from_gdrive_confirmation(res.text)
  File "/usr/local/lib/python3.10/dist-packages/gdown/download.py", line 55, in get_url_from_gdrive_confirmation
    raise FileURLRetrievalError(
gdown.exceptions.FileURLRetrievalError: Cannot retrieve the public link of the file. You may need to change the permission to 'Anyone with the link', or have had many accesses. Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/mimicgen/mimicgen/scripts/download_datasets.py", line 83, in <module>
    FileUtils.download_url_from_gdrive(
  File "/opt/mimicgen/mimicgen/utils/file_utils.py", line 404, in download_url_from_gdrive
    fpath = gdown.download(url, quiet=False, fuzzy=True)
  File "/usr/local/lib/python3.10/dist-packages/gdown/download.py", line 278, in download
    raise FileURLRetrievalError(message)
gdown.exceptions.FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1519sVqkLD6PlI2pir8yjCpyogX1PfjUP

but Gdown can't. Please check connections and permissions.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/mimicgen/mimicgen/generate.py", line 163, in <module>
    main()
  File "/opt/mimicgen/mimicgen/generate.py", line 159, in main
    generate(**vars(args))
  File "/opt/mimicgen/mimicgen/generate.py", line 57, in generate
    download(datasets, cache=cache, **kwargs)
  File "/opt/mimicgen/mimicgen/generate.py", line 126, in download
    run(cmd, **kwargs)
  File "/opt/mimicgen/mimicgen/generate.py", line 138, in run
    subprocess.run(cmd, executable=executable, shell=shell, check=check, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 -m mimicgen.scripts.download_datasets --download_dir /data/datasets/mimicgen --dataset_type source --tasks stack ' returned non-zero exit status 1.
```

**Guess**

I think the error throwing because of the expired link `https://drive.google.com/uc?id=1519sVqkLD6PlI2pir8yjCpyogX1PfjUP`

**Comment by park-jihoon-aiv** [comment]
nanosam project is also same
