### ISSUE TITLE
OSError: libcurand.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by thedevleon** [dusty-nv/jetson-containers#93]
I'm running the container "dustynv/ros:noetic-pytorch-l4t-r32.5.0" (and I also tried the previous one) as I want to use ros-noetic together with pytorch on a Jetson AGX.

However, when I try to import PyTorch, I get the following error:

```
Status: Downloaded newer image for dustynv/ros:noetic-pytorch-l4t-r32.5.0
sourcing   /opt/ros/noetic/setup.bash
ROS_ROOT   /opt/ros/noetic/share/ros
ROS_DISTRO noetic
root@e22d0ae5ddbc:/# python
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 188, in <module>
    _load_global_deps()
  File "/usr/local/lib/python3.6/dist-packages/torch/__init__.py", line 141, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcurand.so.10: cannot open shared object file: No such file or directory
>>> 
```
Any idea what I could be missing or how to fix this?

**Comment by thedevleon** [comment]
Edit: 

Reading the README, I found that one needs to change the default runtime to nvidia if one wants to use pytorch, as seen here:
https://github.com/dusty-nv/jetson-containers#docker-default-runtime
